version: '2'
services:

  postgres:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    command: '-N 500'
    environment:
      - DEBUG=false
      - PG_TRUST_LOCALNET=true
      - PG_PASSWORD=secret
      - DB_NAME=essence-api

  essence:
    image: vitaliyavramenko/essence-api:latest
    container_name: essence-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/essence-api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
    links:
      - "postgres:postgres"
    ports:
      - "8080:8080"
