TRUNCATE users CASCADE;
TRUNCATE product_images CASCADE;
TRUNCATE products CASCADE;
TRUNCATE brands CASCADE;

ALTER SEQUENCE product_images_id_seq RESTART WITH 1000;
ALTER SEQUENCE products_id_seq RESTART WITH 1000;
ALTER SEQUENCE brands_id_seq RESTART WITH 1000;
